<?php 
$bgColor = $this->build->getStatus() == 1?'green': ($this->build->getStatus() == -1 ? 'gray':'red');
?>
<html>
<title>Xinc Dashboard</title>
<head>
<script type="text/javascript" src="/js/tabpane.js"></script>
<script type="text/javascript" src="/js/sortabletable.js"></script>
<link type="text/css" rel="StyleSheet" href="/css/tab.webfx.css" />
<link type="text/css" rel="StyleSheet" href="/css/sortabletable.css" />
<style>
.debug {display:;}
.info {display:;}
</style>
<script type="text/javascript">

function hide(type){
	var idx=0;
	if(type=="debug") idx=0;
	if(type=="info") idx=1;
	document.styleSheets[0].deleteRule(idx); //delete the second rule
	document.styleSheets[0].insertRule('.'+type+' { display:none; }',idx);
}
function show(type){
	var idx=0;
	if(type=="debug") idx=0;
	if(type=="info") idx=1;
	document.styleSheets[0].deleteRule(idx); //delete the second rule
	document.styleSheets[0].insertRule('.'+type+' { display:; }',idx);
}
</script>
</head>
<body>
<?php echo $this->menu; ?>
<table cellspacing="0" cellpadding="5" width="100%">
<tr>
<td colspan="2" valign="top" 	width="70%">

<div class="tab-pane" id="details-tab">
<script type="text/javascript">
tabPane = new WebFXTabPane( document.getElementById( "details-tab" ), true );
</script>
<?php

foreach ($this->getTabs('BUILD_DETAILS') as $tab) {
    echo $tab->generate('tabPane');
}

?>
</div>

<!--  END OF INFO_TAB -->
</td>
<td>
<div class="tab-pane" id="builds-tab">
<script type="text/javascript">
tabPane2 = new WebFXTabPane( document.getElementById( "builds-tab" ), true );
</script>
<?php

foreach ($this->getTabs('BUILD_SELECTOR') as $tab) {
    echo $tab->generate('tabPane2');
}

?>
</div>
</td>
</tr>
</table>
</body>
</html>