<html lang="en" xmlns:ext="http://extjs.com/docs">
<head>
<?php if (($title = Xinc_Ini::getInstance()->get('title', 'web')) !== null) {?>
  <title><?php echo $title; ?> powered by Xinc</title>
  <?php } else { ?>
    <title>Xinc 2.1 - Continuous Integration Server for PHP</title>
    <?php } ?>
    <link rel="stylesheet" type="text/css" href="/extjs/resources/css/ext-all.css" />
    <link rel="stylesheet" type="text/css" href="/css/xinc.css"></link>
    <link rel="stylesheet" type="text/css" href="/extjs/resources/style.css"></link>
    <?php if (($icon = Xinc_Ini::getInstance()->get('icon', 'web')) !== null) {?>
  <link rel="shortcut icon" href="<?php echo $icon; ?>" />
  <link rel="icon" href="<?php echo $icon; ?>" />
  <?php } else { ?>
    <link rel="shortcut icon" href="/images/xinc.ico" />
    <link rel="icon" href="/images/xinc.ico" />
    <?php } ?>

    <style type="text/css">
        </style>

    <!-- GC -->
</head>
<body scroll="no" id="docs">
  <div id="loading-mask" style=""></div>
  <div id="loading">
    <div class="loading-indicator"><img src="/extjs/resources/images/default/shared/large-loading.gif" width="32" height="32" style="margin-right:8px;" align="absmiddle"/>Loading...</div>
  </div>
    <!-- include everything after the loading indicator -->
    <script type="text/javascript" src="/extjs/adapter/ext/ext-base.js"></script>

    <script type="text/javascript" src="/extjs/ext-all.js"></script>
    <script type="text/javascript" src="/extjs/miframe.js"></script>
    <script type="text/javascript" src="/extjs/resources/TabCloseMenu.js"></script>
    <script type="text/javascript" src="/js/xinc.js"></script>
<script>
MenuItems={text:'Menu',children:[],leaf:true};

<?php echo $this->getMenu(); ?>

</script>

  <div id="header">
  
  <div style="float:right;margin-left:5px;margin-right:10px;margin-top:5px;color:white">#ver<?php echo Xinc_Ini::getInstance()->get('version', 'xinc'); ?></div>
    <?php if ( Xinc_Ini::getInstance()->get('ohloh', 'web') == 1) { ?>
    <a href="http://www.ohloh.net/projects/9498?p=Xinc" class="external" target="_new" style="float:right;margin-right:10px;"><img class="external" src="http://www.ohloh.net/projects/9498/widgets/project_thin_badge.gif" style="margin-top:5px;"/></a>
    <?php } ?>
    <?php if (($logo = Xinc_Ini::getInstance()->get('logo', 'web')) !== null) {?>
    <img src="<?php echo $logo; ?>" style="float:left;margin-left:5px;margin-right:10px;"/>
    <?php } else { ?>
    <img src="/images/xinc-logo-white-32x30.png" style="float:left;margin-left:5px;margin-right:10px;"/>
    <?php } ?>
    <?php if (($title = Xinc_Ini::getInstance()->get('title', 'web')) !== null) {?>
    <div class="api-title"><?php echo $title; ?> powered by Xinc</div>
    <?php } else { ?>
    <div class="api-title">Xinc 2.2 - Continuous Integration Server for PHP</div>
    <?php } ?>
  </div>

  <div id="classes"></div>

  <div id="main"></div>
<?php if (($trackerCode = Xinc_Ini::getInstance()->get('trackerCode', 'googleanalytics')) !== null) {?>
<script src="http://www.google-analytics.com/urchin.js" type="text/javascript">
</script>
<script type="text/javascript">
_uacct = "<?php echo $trackerCode; ?>";
urchinTracker();
</script>
<?php } ?>
  </body>
</html>