<style>
.res-block-inner-wide h2
{
font-family: "Trebuchet MS","Bitstream Vera Sans",verdana,lucida,arial,helvetica,sans-serif;
font-weight: bold;
margin-top: 3px;
margin-right: 300px;
margin-bottom: 3px;
margin-left: 0pt;
letter-spacing: 1px;
width: 90%;
font-size: 15px;
padding-top: 20px;
padding-bottom: 5px;
}
</style>
<div class="res-block-wide">

            <div class="res-block-inner-wide">
            <h2>{title}</h2>
            <hr/>
                {content}
            </div>

        </div>