<html lang="en" xmlns:ext="http://extjs.com/docs">
<head>
  <title>Xinc 2.0 - Continuous Integration Server for PHP</title>
    <link rel="stylesheet" type="text/css" href="/ext-2.0/resources/css/ext-all.css" />
    <link rel="stylesheet" type="text/css" href="/ext-2.0/resources/docs.css"></link>
	<link rel="stylesheet" type="text/css" href="/ext-2.0/resources/style.css"></link>
	<link rel="shortcut icon" href="http://www.jackslocum.com/favicon.ico" />
	<link rel="icon" href="http://www.jackslocum.com/favicon.ico" />
	<style type="text/css">
		</style>

	<!-- GC -->
</head>
<body scroll="no" id="docs">
  <div id="loading-mask" style=""></div>
  <div id="loading">
    <div class="loading-indicator"><img src="/ext-2.0/resources/extanim32.gif" width="32" height="32" style="margin-right:8px;" align="absmiddle"/>Loading...</div>
  </div>
    <!-- include everything after the loading indicator -->
    <script type="text/javascript" src="/ext-2.0/adapter/ext/ext-base.js"></script>

    <script type="text/javascript" src="/ext-2.0/ext-all.js"></script>
    <script type="text/javascript" src="/ext-2.0/resources/TabCloseMenu.js"></script>
    <script type="text/javascript" src="/ext-2.0/resources/xinc.js"></script>


  <div id="header">
	<a href="http://extjs.com" class="external" target="_new" style="float:right;margin-right:10px;"><img class="external" src="/ext-2.0/resources/extjs.gif" style="width:83px;height:24px;margin-top:1px;"/></a>

	<div class="api-title">Xinc 2.0 - Continuous Integration Server for PHP</div>
  </div>

  <div id="classes"></div>

  <div id="main"></div>
  <!-- <select id="search-options" style="display:none">
    <option>Starts with</option>

    <option>Ends with</option>
    <option>Any Match</option>
</select>-->
<script src="http://www.google-analytics.com/urchin.js" type="text/javascript">
</script>
<script type="text/javascript">
_uacct = "UA-1346205-4";
urchinTracker();
</script>
  </body>
</html>