#!/usr/bin/env php
<?php
/**
 * Xinc - Cross integration and continous management.
 * This script belongs to the Xinc Server.
 *
 * It is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License, either version 3
 * of the License, or (at your option) any later version.
 *
 * PHP version 5
 *
 * @category Development
 * @package  Xinc.Packager
 * @author   Alexander Opitz <opitz.alexander@googlemail.com>
 * @license  http://www.gnu.org/copyleft/lgpl.html GNU LGPL 3+
 * @link     http://code.google.com/p/xinc/
 */

require_once __DIR__ . '/../../../Libraries/autoload.php';

Xinc\Server\Xinc::execute();
