<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <?php if (($title = Xinc_Ini::getInstance()->get('title', 'web')) !== null) {?>
    <title><?php echo $title; ?> powered by Xinc</title>
    <?php } else { ?>
    <title>Xinc 2.3 - Continuous Integration Server for PHP</title>
    <?php } ?>
    <link rel="stylesheet" type="text/css" href="./extjs/resources/css/ext-all.css" />
    <link rel="stylesheet" type="text/css" href="./css/xinc.css" />
    <link rel="stylesheet" type="text/css" href="./css/style.css" />
    <?php if (($icon = Xinc_Ini::getInstance()->get('icon', 'web')) !== null) {?>
    <link rel="shortcut icon" href="<?php echo $icon; ?>" />
    <link rel="icon" href="<?php echo $icon; ?>" />
    <?php } else { ?>
    <link rel="shortcut icon" href="./images/xinc.ico" />
    <link rel="icon" href="./images/xinc.ico" />
    <?php } ?>
</head>

<body scroll="no" id="docs">
    <div id="loading">
        <div class="loading-indicator">Loading...</div>
    </div>

    <script type="text/javascript" src="./extjs/ext-all-debug.js"></script>
    <script>
        MenuItems={text:'Menu',children:[],expanded:true};
        <?php echo $this->getMenu(); ?>
    </script>
    <script type="text/javascript" src="./js/xinc.js"></script>
    <div id="header-content" style="display:none">
        <div style="float:right;margin-left:5px;margin-right:10px;margin-top:5px;color:white">#ver<?php echo Xinc_Ini::getInstance()->get('version', 'xinc'); ?></div>
        <?php if ( Xinc_Ini::getInstance()->get('ohloh', 'web') == 1) { ?>
        <a href="http://www.ohloh.net/p/xinc-continuous-integration-for-php" class="external" target="_new" style="float:right;margin-right:10px;">
            <img class="external" src="http://www.ohloh.net/p/xinc-continuous-integration-for-php/widgets/project_thin_badge.gif" style="margin-top:5px;"/>
        </a>
        <?php } ?>
        <?php if (($logo = Xinc_Ini::getInstance()->get('logo', 'web')) !== null) {?>
        <img src="<?php echo $logo; ?>" style="float:left;margin-left:5px;margin-right:10px;"/>
        <?php } else { ?>
        <img src="./images/xinc-logo-white-32x30.png" style="float:left;margin-left:5px;margin-right:10px;"/>
        <?php } ?>
        <?php if (($title = Xinc_Ini::getInstance()->get('title', 'web')) !== null) {?>
        <div class="api-title"><?php echo $title; ?> powered by Xinc</div>
        <?php } else { ?>
        <div class="api-title">Xinc 2.3 - Continuous Integration Server for PHP</div>
        <?php } ?>
    </div>
</body></html>
