<html>
<head>
<link rel="stylesheet" type="text/css" href="/ext-2.0/resources/css/ext-all.css" />
    <link rel="stylesheet" type="text/css" href="/css/xinc.css"></link>
    	<link rel="stylesheet" type="text/css" href="/ext-2.0/resources/style.css"></link>

<script src="/plotkit/lib/prototype/prototype.js" type="text/javascript"></script>
		<script src="/plotkit/lib/excanvas/excanvas.js" type="text/javascript"></script>
		<script src="/plotkit/plotr_uncompressed.js" type="text/javascript"></script>
</head>
<body>
    <div id="test" class="col">
    <div id="graphs"  class="body-wrap" height="1000px">
<?php

echo $this->getGraphs();

?>
 </div>
 </div>
 </body>
 </html>