<html>
<head>
<style>
*|h1, *|h2, *|h3, *|h4, *|h5, *|h6
{
font-family: "Trebuchet MS","Bitstream Vera Sans",verdana,lucida,arial,helvetica,sans-serif;
font-weight: bold;
letter-spacing: 1px;
font-size:100%;
}
</style>
<script src="/plotkit/lib/prototype/prototype.js" type="text/javascript"></script>
		<script src="/plotkit/lib/excanvas/excanvas.js" type="text/javascript"></script>
		<script src="/plotkit/plotr.js" type="text/javascript"></script>
</head>
<body style="overflow-y: auto">
    <div id="test" class="col">
    <div id="graphs"  class="body-wrap" height="1000px">
<?php

echo $this->getGraphs();

?>
 </div>
 </div>
 </body>
 </html>