
<tr class="config-row alt">
<td class="micon"><a class="exi" href="#expand">&nbsp;</a></td>
        <td class="msource"><b>Revision</b>: {revision}</td>
<td  class="msource"><b>Author</b>: {author}</td>
</tr>
<tr class="config-row alt {expandable}">
<td class="micon"><a class="exi" href="#expand">&nbsp;</a></td>

<td class="sig" colspan="2">
        <a id="Ext.Action-iconCls"></a>
                        {message}
        </td>

        </tr>
