<table border="0" cellspacing="0" cellpadding="0">
<tr>
<td width="50%"><strong>Previous Revision:</strong></td><td width="40%">{previous_revision}</td>
</tr>
<tr>
<td><strong>Revision:</strong></td><td>{current_revision}</td>
</tr>
<tr>
<td><strong>Files Modified</strong></td><td>{files_modified}</td>
</tr>
<tr>
<td><strong>Files Added</strong></td><td>{files_added}</td>
</tr>
<tr>
<td><strong>Files Deleted</strong></td><td>{files_deleted}</td>
</tr>
<tr>
<td><strong>Files Merged</strong></td><td>{files_merged}</td>
</tr>
<tr>
<td><strong>Files in conflict</strong></td><td>{files_conflicted}</td>
</tr>
</table>
